config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts
  resources :properties
  
  # Admin Route
  get "/accounts" => 'admin#accounts', as: :accounts
  
  # Public Pages
  get "/propertylist" => 'public#properties', as: :propertylist
  get "/advertizing" => 'public#advertizing', as: :advertizing
  get "/realtors" => 'public#realtors', as: :realtors
  get "/loans" => 'public#loans', as: :loans
  get "/contact" => 'public#contact', as: :contact

  get "/dashboard" => 'dashboard#index', as: :dashboard
  get "/profile:id" => 'properties#profile', as: :profile
  post "/agent/viewing" => 'properties#viewing', as: :viewing 
  
  # Root Page
  root to: 'public#main'
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable

  has_one_attached :image
  
  has_many :properties

  def full_name
    "#{first_name} #{last_name}"
  end

 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/property.rb
class Property < ApplicationRecord
    has_many_attached :images
    belongs_to :account

    validate :image_type

    def thumbnail input
        return self.images[input].variant(resize: '200x200!')
    end

    

    private
    def image_type
        if images.attached? == false
            errors.add(:images, 'are missing!')
    end
    images.each do |image|
        if !image.content_type.in?(%('image/jpeg image/jpg image/png'))
            errors.add(:images, 'need to be a JPG, JPEG or PNG')
        end
    end
    end
    
    scope :latest, -> { order created_at: :desc }
 end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
    before_action :can_access?

    def accounts
        @accounts = Account.where(admin: false)
    end

    def can_access?
        unless current_account.admin?
            redirect_to root_url, flash: { danger: "You do not have access to view this page" } and return
        end
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :telephone, :url, :company, :image, :image_cache  ])
        devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :set_sidebar

  def index
  end

 

  private

  def set_sidebar
    @show_sidebar = true
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: %i[ show edit update destroy ]
  before_action :authenticate_account!, only: %i[ new edit update destroy ]
  before_action :set_sidebar, except: [:show]
  

  # GET /properties or /properties.json
  def index
    @properties = Property.all
    
  end

  # GET /properties/1 or /properties/1.json
  def show
   @agent = @property.account
   @agent_properties = Property.where(account_id: @agent.id).where.not(id: @property.id).limit(3)
  end

    # GET /properties/new
  def new
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
  end

  def profile
    @account = Account.find(params[:id])
  end

  # POST /properties or /properties.json
  def create
    @property = Property.new(property_params)
    @property.account_id = current_account.id

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: "Property was successfully created." }
        format.json { render :show, status: :created, address: @property }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1 or /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: "Property was successfully updated." }
        format.json { render :show, status: :ok, address: @property }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1 or /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: "Property was successfully deleted." }
      format.json { head :no_content }
    end
  end

  def book_viewing
    agent_id = params[:agent_id]
    first_name = params[:first_name]
    last_name = params[:last_name]
    email = params[:email]  
    phone = params[:phone]

    ViewingMailer.viewing( agent_id, first_name, last_name, email, phone ).deliver_now

    respond_to do |format|
      format.json { head :no_content }
    end
  end

  def correct_account
    @property = current_account.properties.find(id: params[:id])
    redirect_to properties_path, notice: "Not Authorized to Edit this Property" if @property.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    def set_sidebar
      @show_sidebar = true
    end


    # Only allow a list of trusted parameters through.
    def property_params
      params.require(:property).permit(:name, :address, :price, :rooms, :bathrooms, :for_rent, :available_date, :details, images: [] )
    end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
   def main
      if account_signed_in?
         path = current_account.admin? ? accounts_path : dashboard_path
         redirect_to path, flash: { notice: "Successfully signed in, Welcome to saraari" } and return
      end

      @properties = Property.latest
   end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def profile_picture account 
        thumb = account.image.present? ? account.image : "account-placeholder.png"
        image_tag thumb, class: "profile-pic img-circle"    
    end

    def flash_notifications
        flash_messages = []

        flash.each do |type, message|
            type = 'success' if type == 'notice'
            type = 'error' if type == 'alert' || type == 'danger'
            text = "toastr['#{type}']('#{message}');"
            flash_messages << text.html_safe unless message.blank?
        end

    "<script>$(function(){ #{ flash_messages.join("\n") } });</script>".html_safe if flash_messages.any?
    end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper

        def property_thumbnail property
            img = property.images.present? ? property.images[0] : "placeholder.jpg"
            image_tag img, class:"property-thumb"
        end

        def property_photo_url property
            property.images.present? ? property.images[0] : asset_url("placeholder.jpg")
        end
    
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/admin/accounts.html.erb
<p id="notice"><%= notice %></p> 

<div class="chartjs-size-monitor"><div class="chartjs-size-monitor-expand"><div class=""></div></div><div class="chartjs-size-monitor-shrink"><div class=""></div></div></div>
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Accounts</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
          <div class="btn-group me-2">
            <button type="button" class="btn btn-sm btn-outline-secondary">Share</button>
            <button type="button" class="btn btn-sm btn-outline-secondary">Export</button> 
          </div>
          <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-calendar"><rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect><line x1="16" y1="2" x2="16" y2="6"></line><line x1="8" y1="2" x2="8" y2="6"></line><line x1="3" y1="10" x2="21" y2="10"></line></svg>
            This week
          </button>
        </div>
      </div>
      <div class="table-responsive">
        <table class="table table-striped table-sm">
          <thead>
            <tr>
              <th>Account ID</th>
              <th>Full Name</th>
              <th>Company</th>
              <th>Email Address</th>
              <th>Created At</th>
              <th>View Profile</th>
            </tr>
          </thead>
          <tbody>
            <% @accounts.each do |account| %>
            <tr>
              <td>1,001</td>
              <td><%= account.full_name %></td>
              <td><%= account.company %></td>
              <td><%= account.email %></td>
              <td><%= account.created_at.strftime("%d %m %Y") %></td>
              <td><%= link_to "View Profile", profile_path(account.id), class: "btn btn-sm btn-outline-secondary" %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
</div>

app/views/dashboard/properties.html.erb
<h1>Dashboard#properties</h1>
<p>Find me in app/views/dashboard/properties.html.erb</p>

app/views/dashboard/reports.html.erb
<h1>Dashboard#reports</h1>
<p>Find me in app/views/dashboard/reports.html.erb</p>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/nav/_dashboard.html.erb
<header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
  <a href="<%= account_signed_in? ? dashboard_path : root_path %>"><span class="fs-4 text-white">saraari</span></a>
  <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
  <ul class="navbar-nav px-3">
    <li class="nav-item text-nowrap">
    <%= link_to "Sign Out", destroy_account_session_path, method: :delete, class: "nav-link" %>
    </li>
  </ul>
</header>

app/views/layouts/nav/_public.html.erb
<header class="navbar navbar-dark bg-dark navbar-expand-md fixed-top shadow">
    <div class="container-fluid">
    <a href="<%= account_signed_in? ? dashboard_path : root_path %>"><span class="fs-4 text-white">saraari</span></a>
    
  
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
        <li class="nav-item">
            &nbsp; &nbsp;
            &nbsp; &nbsp;
            &nbsp; &nbsp;
            &nbsp; &nbsp;
            &nbsp; &nbsp;
            &nbsp; &nbsp;
 
          </li>
          <% if account_signed_in?%>
          <li class="nav-item">
              <%= link_to 'Dashboard', dashboard_path, class:"nav-link"%>
            </li>
          <% else %>
          <% end %>
        <li class="nav-item">
            <a class="nav-link " href="/">Home</a>
          </li>
           
          <li class="nav-item dropdown">
            <%= link_to 'Properties',  propertylist_path, class: "nav-link dropdown-toggle", id: "navbarDropdownMenuLink" %>
            
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <li><a class="dropdown-item" href="#">Selling</a></li>
              <li><a class="dropdown-item" href="#">Renting</a></li>
            </ul>
        </li>
        
          <li class="nav-item">
          <%= link_to 'Advertizing',  advertizing_path, class: "nav-link"%>
          </li>
          <li class="nav-item">
          <%= link_to 'Realtors',  realtors_path, class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to 'Home Loans',  loans_path, class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to 'Contact Us',  contact_path, class: "nav-link"%>
          </li>
          
           
          
        </ul>
        <form class="d-flex">
        <% if account_signed_in? %>
             <li class="nav-item">
              <%= link_to 'Profile',  edit_account_password_path, class:"btn btn-sm btn-outline-secondary"%>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign Out', destroy_account_session_path, method: :delete, class:"btn btn-sm btn-outline-danger"%>
            </li>

          <% else %>
          <%= link_to 'Log In', new_account_session_path, class:"btn btn-sm btn-outline-secondary"%>
        
        <% end %>

        </form>
      </div>
    </div>
  </header>

app/views/layouts/nav/_sidebar.html.erb
 <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="position-sticky pt-3">
        <ul class="nav flex-column">
          <%= render "layouts/nav/#{ current_account.admin? ? 'admin' : 'user' }" %>
        </ul>

        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
          <span>Settings</span>
        </h6>
        <ul class="nav flex-column mb-2">
          <li class="nav-item">
            <%= link_to profile_path(current_account), class: "nav-link" do %>
               <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="purple" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-user"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/></svg>
              Profile
           <% end %>
          </li>
          <li class="nav-item">
            <%= link_to edit_account_registration_path, class: "nav-link" do %>
               <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="purple" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-settings"><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1 0 2.83 2 2 0 0 1-2.83 0l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-2 2 2 2 0 0 1-2-2v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83 0 2 2 0 0 1 0-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1-2-2 2 2 0 0 1 2-2h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 0-2.83 2 2 0 0 1 2.83 0l.06.06a1.65 1.65 0 0 0 1.82.33H9a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 2-2 2 2 0 0 1 2 2v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 0 2 2 0 0 1 0 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82V9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 2 2 2 2 0 0 1-2 2h-.09a1.65 1.65 0 0 0-1.51 1z"/></svg>
              Account Settings
           <% end %>
          </li>
          
        </ul>
      </div>
    </nav>

app/views/properties/_latest_properties.html.erb
<% properties.each do |property| %>   
        <div class="col">
            <div class="card shadow-sm" style="width:300">
                <%= property_thumbnail property %>
                <div class="card-body">
                    <h5 class="card-title"><%= link_to property.name, property_path(property) %></h5>
                    
                    <span><svg class="domain-icon css-1odb7b6" width="24" height="24" viewBox="0 0 24 24" aria-hidden="true"><path fill="none" stroke="currentColor" stroke-width="2" d="M4.00002 19.00001v2M20.00002 19.00001v2M8 11h8a5 5 0 0 1 5 5v3H3v-3a5 5 0 0 1 5-5z"></path><path d="M6.5 11V9A1.5 1.5 0 0 1 8 7.5h2A1.5 1.5 0 0 1 11.5 9v1M12.5 10V9A1.5 1.5 0 0 1 14 7.5h2A1.5 1.5 0 0 1 17.5 9v2" fill="none" stroke="currentColor"></path><path d="M20 13V5a2 2 0 0 0-2-2H6a2 2 0 0 0-2 2v8" fill="none" stroke="currentColor" stroke-width="2"></path><path fill="none" stroke="currentColor" d="M3.5 15.5h17"></path></svg> <%= property.rooms %></span>
                    <span><svg class="domain-icon css-1odb7b6" width="24" height="24" viewBox="0 0 24 24" aria-hidden="true"><path fill="none" stroke="currentColor" stroke-width="2" d="M6 19v2M18 19v2"></path><g fill="currentColor"><circle cx="15.5" cy="8.5" r=".5"></circle><circle cx="13.5" cy="8.5" r=".5"></circle><circle cx="11.5" cy="8.5" r=".5"></circle><circle cx="13.5" cy="6.5" r=".5"></circle><circle cx="13.5" cy="10.5" r=".5"></circle><circle cx="11.5" cy="10.5" r=".5"></circle><circle cx="17.5" cy="10.5" r=".5"></circle><circle cx="15.5" cy="10.5" r=".5"></circle></g><g fill="none" stroke="currentColor" stroke-width="2"><path d="M4 13h16v2a5 5 0 0 1-5 5H9a5 5 0 0 1-5-5v-2zM4 12V7a3 3 0 0 1 3-3h1"></path><path d="M8 6.3V4a1 1 0 0 1 1-1h2.3a.7.7 0 0 1 .5 1.2L9.2 6.8A.7.7 0 0 1 8 6.3zM3 13h18"></path></g></svg> <%= property.bathrooms %></span>
                    
                    <p class="card-text"><em>Location: </em><%= property.address %></p>                 
                </div>
                <div class="card-footer">
                <small class="text-muted"><%= link_to 'View Property', property, class: "btn btn-sm btn-outline-secondary" %> </small>
                </div>
            </div>
        </div>    
<% end %>

app/views/properties/_list.html.erb
 <%= properties.each do |property| %>   
        <div class="col-4">
            <div class="card shadow-sm w-200">
                <%= property_thumbnail property %>
                <div class="card-body">
                    <h5 class="card-title"><%= link_to property.name, property_path(property) %></h5>
                    
                    <span><svg class="domain-icon css-1odb7b6" width="24" height="24" viewBox="0 0 24 24" aria-hidden="true"><path fill="none" stroke="currentColor" stroke-width="2" d="M4.00002 19.00001v2M20.00002 19.00001v2M8 11h8a5 5 0 0 1 5 5v3H3v-3a5 5 0 0 1 5-5z"></path><path d="M6.5 11V9A1.5 1.5 0 0 1 8 7.5h2A1.5 1.5 0 0 1 11.5 9v1M12.5 10V9A1.5 1.5 0 0 1 14 7.5h2A1.5 1.5 0 0 1 17.5 9v2" fill="none" stroke="currentColor"></path><path d="M20 13V5a2 2 0 0 0-2-2H6a2 2 0 0 0-2 2v8" fill="none" stroke="currentColor" stroke-width="2"></path><path fill="none" stroke="currentColor" d="M3.5 15.5h17"></path></svg> <%= property.rooms %></span>
                    <span><svg class="domain-icon css-1odb7b6" width="24" height="24" viewBox="0 0 24 24" aria-hidden="true"><path fill="none" stroke="currentColor" stroke-width="2" d="M6 19v2M18 19v2"></path><g fill="currentColor"><circle cx="15.5" cy="8.5" r=".5"></circle><circle cx="13.5" cy="8.5" r=".5"></circle><circle cx="11.5" cy="8.5" r=".5"></circle><circle cx="13.5" cy="6.5" r=".5"></circle><circle cx="13.5" cy="10.5" r=".5"></circle><circle cx="11.5" cy="10.5" r=".5"></circle><circle cx="17.5" cy="10.5" r=".5"></circle><circle cx="15.5" cy="10.5" r=".5"></circle></g><g fill="none" stroke="currentColor" stroke-width="2"><path d="M4 13h16v2a5 5 0 0 1-5 5H9a5 5 0 0 1-5-5v-2zM4 12V7a3 3 0 0 1 3-3h1"></path><path d="M8 6.3V4a1 1 0 0 1 1-1h2.3a.7.7 0 0 1 .5 1.2L9.2 6.8A.7.7 0 0 1 8 6.3zM3 13h18"></path></g></svg> <%= property.bathrooms %></span>
                    
                    <p class="card-text"><em>Location: </em><%= property.address %></p>                 
                </div>
                <div class="card-footer">
                    <small class="text-muted"><%= link_to 'View Property', property, class: "btn btn-sm btn-outline-secondary" %> </small>
                </div>
            </div>
        </div>   
<% end %>

app/views/properties/_properties.html.erb
<% Property.all.each do |property| %>   
        <div class="col">
            <div class="card shadow-sm" style="width:100">
                <%= property_thumbnail property %>
                <div class="card-body">
                    <h5 class="card-title"><%= link_to property.name, property_path(property) %></h5>
                    
                    <span><svg class="domain-icon css-1odb7b6" width="24" height="24" viewBox="0 0 24 24" aria-hidden="true"><path fill="none" stroke="currentColor" stroke-width="2" d="M4.00002 19.00001v2M20.00002 19.00001v2M8 11h8a5 5 0 0 1 5 5v3H3v-3a5 5 0 0 1 5-5z"></path><path d="M6.5 11V9A1.5 1.5 0 0 1 8 7.5h2A1.5 1.5 0 0 1 11.5 9v1M12.5 10V9A1.5 1.5 0 0 1 14 7.5h2A1.5 1.5 0 0 1 17.5 9v2" fill="none" stroke="currentColor"></path><path d="M20 13V5a2 2 0 0 0-2-2H6a2 2 0 0 0-2 2v8" fill="none" stroke="currentColor" stroke-width="2"></path><path fill="none" stroke="currentColor" d="M3.5 15.5h17"></path></svg> <%= property.rooms %></span>
                    <span><svg class="domain-icon css-1odb7b6" width="24" height="24" viewBox="0 0 24 24" aria-hidden="true"><path fill="none" stroke="currentColor" stroke-width="2" d="M6 19v2M18 19v2"></path><g fill="currentColor"><circle cx="15.5" cy="8.5" r=".5"></circle><circle cx="13.5" cy="8.5" r=".5"></circle><circle cx="11.5" cy="8.5" r=".5"></circle><circle cx="13.5" cy="6.5" r=".5"></circle><circle cx="13.5" cy="10.5" r=".5"></circle><circle cx="11.5" cy="10.5" r=".5"></circle><circle cx="17.5" cy="10.5" r=".5"></circle><circle cx="15.5" cy="10.5" r=".5"></circle></g><g fill="none" stroke="currentColor" stroke-width="2"><path d="M4 13h16v2a5 5 0 0 1-5 5H9a5 5 0 0 1-5-5v-2zM4 12V7a3 3 0 0 1 3-3h1"></path><path d="M8 6.3V4a1 1 0 0 1 1-1h2.3a.7.7 0 0 1 .5 1.2L9.2 6.8A.7.7 0 0 1 8 6.3zM3 13h18"></path></g></svg> <%= property.bathrooms %></span>
                    
                    <p class="card-text"><em>Location: </em><%= property.address %></p>                 
                </div>
                <div class="card-footer">
                <small class="text-muted"><%= link_to 'View Property', property, class: "btn btn-sm btn-outline-secondary" %> </small>
                </div>
            </div>
        </div>    
<% end %>

app/views/properties/_viewing_modal.html.erb
<div class="modal fade" id="viewing-modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Book a Viewing for <%= @property.name %> </h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= form_tag viewing_path, id: "book-viewing", method: :post do %>
          <% hidden_field_tag :agent_id, @agent.id %>
          
          <div class="form-group">
            <label for="viewing-first-name" class="col-form-label" id="viewing-first-name">First Name:</label>
            <%= text_field_tag :first_name, nil, class: "form-control", id: "viewing-first-name" %>
          </div>
          <div class="form-group">
            <label for="viewing-last-name" class="col-form-label" id="viewing-last-name">Last Name:</label>
            <%= text_field_tag :last_name, nil, class: "form-control", id: "viewing-last-name" %>
          </div>
          <div class="form-group">
            <label for="viewing-email" class="col-form-label" id="viewing-email">Email Address:</label>
            <%= text_field_tag :email, nil, class: "form-control", id: "viewing-email" %>
          </div>
          <div class="form-group">
            <label for="viewing-phone" class="col-form-label" id="viewing-phone">Phone Number:</label>
            <%= text_field_tag :phone, nil, class: "form-control", id: "viewing-phone" %>
          </div>
          
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-success" id="book-viewing">Book Viewing</button>
      </div>
    </div>
  </div>
</div>

app/views/properties/edit.html.erb
<h1 class="h3">Editing Property</h1>

<%= render 'form', property: @property %>
<br>

app/views/properties/index.html.erb
<p id="notice"><%= notice %></p> 

<h1 class="h3">Properties</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th>Price</th>
      <th>Rooms</th>
      <th>Bathrooms</th>
      <th>Account ID</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @properties.each do |property| %>
    
      <tr>
        <td><%= property.name %></td>
        <td><%= property.address %></td>
        <td><%= property.price %></td>
        <td><%= property.rooms %></td>
        <td><%= property.bathrooms %></td>
        <td><%= property.account_id %> </td>
        <td colspan=2 >
        <div class="btn-group me-2">
        <%= link_to 'Show', property, class: "btn btn-outline-secondary btn-sm" %>
        <%= link_to 'Edit', edit_property_path(property), class: "btn btn-outline-dark btn-sm" %>
        </div></td>
        <td><%= link_to 'Remove', property, method: :delete, class: "btn btn-danger btn-sm", data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Property', new_property_path, class: "btn btn-success" %>

app/views/properties/new.html.erb
<h1 class="h3">New Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Back', properties_path %>

app/views/properties/profile.html.erb
<p>
<%= @account.full_name %>
</p>